import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
// import { appWithTranslation } from 'next-i18next';
// import { i18n } from '../../next-i18next.config.mjs';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}

// export default appWithTranslation(RootLayout, { ...i18n });
